### PR TITLE
3.6 compatibility

### PR DESCRIPTION
**Pull request by hategan**
The problem was caused by "from __future__ import annotations", which is there to support forward type definitions (e.g., `class A: def fn(a: A):...` instead of having to quote A - `class A: def fn(a: 'A'):...`)

### CODE REVIEW

**Review by andre-merzky — APPROVED** [review]
LGTM

**Review by SteVwonder — APPROVED** [review]
LGTM!

**Comment by SteVwonder** [comment]
Now that #6 is in, do we want to squash and merge this?  Or rebase it?  Not sure how much we care about the duplicate commits.

**Comment by hategan** [comment]
> Now that #6 is in, do we want to squash and merge this? Or rebase it? Not sure how much we care about the duplicate commits.

This was rebased on #6, so should be fine now that #6 has been merged.

**Comment by hategan** [comment]
@andre-merzky, @SteVwonder, can I merge this?

**Comment by andre-merzky** [comment]
From my end yes, and happy to push the button.  Please let me use that opportunity for a question though: @SteVwonder: should the merge commit be squashed into a single commit, or is that up to the owner of the PR?

**Comment by SteVwonder** [comment]
> @andre-merzky, @SteVwonder, can I merge this?

Yeah. I was initially confused by the Github diff, since it appears to show this PR adding the entire contents of the workflow yaml.  I pulled down the branch and `git diff upstream/master` and that made way more sense.  Sorry, not used to reviewing PRs that have merge commits in them.

> Please let me use that opportunity for a question though: @SteVwonder: should the merge commit be squashed into a single commit, or is that up to the owner of the PR?

I don't think we have that documented anywhere.  In a rebase-based fork/pull or C4 gitflow, I think you would normally leave all the commits since they will apply cleanly and you keep the more precise history.  Idk what is typically done in gitflow, for example.  I know Spack makes extensive use of "squash and merge".  What are you two more accustomed to?

For this PR, I think it may make more sense to do a "squash and merge".  I'll leave that choice up to @hategan though.  Any preference @hategan?

**Comment by hategan** [comment]
> I know Spack makes extensive use of "squash and merge". What are you two more accustomed to?

I try to keep my commits small on purpose, so squashing would seem silly to me, but maybe I'm missing something.

**Comment by andre-merzky** [comment]
>  Idk what is typically done in gitflow, for example.

We usually leave all commits, for two reasons: (a) we don't care about clean history :-P, (b) it makes `git bisect` more efficient.

Thanks both!

**Pull request merged**
