### PR TITLE
Use pystache fork for now and also add all relevant dependencies to r…

### PR DESCRIPTION
**Pull request by hategan**
…equirements-dev

### CODE REVIEW

**Review by jameshcorbett — APPROVED** [review]
LGTM although there are some conflicts abd I will let @andre-merzky approve as well. Also the other day I learned a neat trick for requirements files: https://stackoverflow.com/questions/11704287/split-requirements-files-in-pip so we don't have to list ``psutil`` and so on in both files.

**Comment by hategan** [comment]
> although there are some conflicts

Oops. Sorry. Fixed.

**Comment by hategan** [comment]
> Also the other day I learned a neat trick for requirements files

Yes, we should probably use that.

**Review by andre-merzky — APPROVED** [review]
LGTM

**Comment by hategan** [comment]
BTW, https://github.com/PennyDreadfulMTG/pystache has now made a release (not pypi yet, just github) and added a tag. So we may want to switch to that.

**Pull request merged**
