### PR TITLE
Add flake8 docstrings

### PR DESCRIPTION
**Pull request by hategan**
This enables additional checks for docstring formatting.

The PR also contains some docstring fixes to make it actually work.

### CODE REVIEW

**Review by jameshcorbett — APPROVED** [review]
Looks great, especially the new ``Descriptor`` docstring. Does having flake8-docstring installed make docstring checks run automatically with flake8?

**Comment by hategan** [comment]
> Does having flake8-docstring installed make docstring checks run automatically with flake8?

I'm going to assume so. I'm doing this because I noticed that I was getting errors locally when the git tests would pass. So I set to investigate why, and I noticed that flake8 had that plugin installed. I suppose we can test it.

**Comment by hategan** [comment]
Hmm, not sure why only two tests are running.

**Comment by hategan** [comment]
>> Does having flake8-docstring installed make docstring checks run automatically with flake8?
> I suppose we can test it.

Looks like it.

**Pull request merged**
