### PR TITLE
Alternate file deployment scheme 2

### PR DESCRIPTION
**Pull request by hategan**
This is an alternative to #220. The problem with #220 was that each new process would create a new directory, but there was no reasonable way to clean these directories. Cleaning too frequently could interfere with debugging and would be incompatible with long-running detached jobs. Setting arbitrary ages, such as 2 days or one month is equally distasteful.

This PR changes launcher so that each launcher instance deploys all its files at once, since these files may reference one another. It does the deployment in directories named as checksums of the contents of the files within. Changing one of the respective files in the source would result in new directories and, more importantly, unchanged launcher files would not. This minimizes clutter enough that manual cleaning is feasible if at all necessary. 

Note: this PR is on top of the more_tests branch, so it looks big. Compare accordingly when reviewing.

### CODE REVIEW

**Review by andre-merzky — COMMENTED** [review]
Yeah, the diff is large because of the other PRs.  If you don't mind I'd rather review when those are merged.

Meanwhile though: I don't get the rationale for the hash, really: what advantage does it have over using the job ID?  It seems it only makes things harder to debug and harder to reproduce.  And the cleanup problem should stay the same I think - or am I missing something?

**Comment by hategan** [comment]
> Yeah, the diff is large because of the other PRs. If you don't mind I'd rather review when those are merged.

Yeah, it was supposed to be on top of more_tests. Not sure how to make it show the diff against that.

> 
> Meanwhile though: I don't get the rationale for the hash, really: what advantage does it have over using the job ID?

Once per unique set of launcher files vs. once per job. The first should only generate one dir for a given launcher and a given (unmodified) version of psi/j. There is no cleanup, since we don't expect this list to grow too large.

If we do per job, we're back to the "when do we clean" problem (i.e., 2 hours, 2 days, when process ends, how about jobs we plan to re-attach to, etc.)

**Review by andre-merzky — APPROVED** [review]
Oh, of course - the assumption is that the launcher script is independent of the job itself and thus remains unchanged between job invocations...  Well, fair, as long as this is the case this works.  I am still not a big fan of hash-generated directory and file names, but I also don't see anything wrong with it really: it solves the problem at hand.  Thanks!

**Comment by hategan** [comment]
> Yeah, the diff is large because of the other PRs. If you don't mind I'd rather review when those are merged.

@andre-merzky, should be more manageable now

**Pull request merged**
