### PR TITLE
This logs sys.path, but removes explicit references to home directories.

### PR DESCRIPTION
**Pull request by hategan**

### CODE REVIEW

**Comment by benclifford** [comment]
what is this for? logging to the central log server? or using the paths for some other purpose?

**Comment by hategan** [comment]
> what is this for? logging to the central log server? or using the paths for some other purpose?

Sorry. Yes, logs to the central server the python path that the tests are running under.

**Comment by benclifford** [comment]
Merged this, with the disclosure that I kinda have a bad feeling about doing clever substitutions that make it look like a setting is set to something other than what it is, from debugging frustrations in the past.

**Comment by hategan** [comment]
> Merged this, with the disclosure that I kinda have a bad feeling about doing clever substitutions that make it look like a setting is set to something other than what it is, from debugging frustrations in the past.

This may have a simple solution: make it obvious. E.g., "<home>/" instead of "~/"

**Pull request merged**
