### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by hategan**
This adds navigation and linking to the docs.

It also fixes some issues with parts of the docs not visible and adds styling to have the docs match the site more.

### CODE REVIEW

**Comment by jameshcorbett** [comment]
How can I look at the changes? When I ``make docs; cd web; python -m http.server``, the documentation is a 404 (not unique to this PR). And pulling up the documentation separately gives me the usual readthedocs styling.

**Comment by hategan** [comment]
> How can I look at the changes? When I `make docs; cd web; python -m http.server`, the documentation is a 404 (not unique to this PR). And pulling up the documentation separately gives me the usual readthedocs styling.

From the main dir, run `./web/build.sh`. The output should be in `./web-build`, where you can start `http.server`.

**Comment by hategan** [comment]
> From the main dir, run `./web/build.sh`. The output should be in `./web-build`, where you can start `http.server`

Should probably add a target in the makefile...

**Comment by jameshcorbett** [comment]
> > How can I look at the changes? When I `make docs; cd web; python -m http.server`, the documentation is a 404 (not unique to this PR). And pulling up the documentation separately gives me the usual readthedocs styling.
> 
> From the main dir, run `./web/build.sh`. The output should be in `./web-build`, where you can start `http.server`.

Thanks. I notice now that some sub-headings in the docs have a larger font size than their parent headings. See e.g. "Getting Started" -> "Adding Complexity" vs "Getting Started" -> "Adding Complexity" -> "Multiple Jobs"

**Comment by hategan** [comment]
> Thanks. I notice now that some sub-headings in the docs have a larger font size than their parent headings. See e.g. "Getting Started" -> "Adding Complexity" vs "Getting Started" -> "Adding Complexity" -> "Multiple Jobs"

Thanks for noticing. Should be fixed now.

**Pull request merged**
