### PR TITLE
Rename psi.j package to psij

### PR DESCRIPTION
**Pull request by jameshcorbett**
Closes ExaWorks#15.

### CODE REVIEW

**Comment by jameshcorbett** [comment]
Rebased to be even with main after merging of #43.

**Review by andre-merzky — APPROVED** [review]
Seems to work as expected, and LGTM - thanks!

**Comment by SteVwonder** [comment]
LGTM too!  Looks like the doc building is broken due to #44 and not due to the PR.

**Review by hategan — APPROVED** [review]
+1 :)

**Pull request merged**
