### PR TITLE
rp: add missing `Dict` import from `typing`

### PR DESCRIPTION
**Pull request by SteVwonder**
Problem: `import psi.j` fails with:
```
❯ python3 -c 'import psi.j'                                                                                                                                                                                19:51:33 ()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 74, in <module>
    _find_plugins(path, type, 0)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 63, in _find_plugins
    _find_plugins(path + os.path.sep + mod.name, type, ix + 1)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 63, in _find_plugins
    _find_plugins(path + os.path.sep + mod.name, type, ix + 1)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 63, in _find_plugins
    _find_plugins(path + os.path.sep + mod.name, type, ix + 1)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 59, in _find_plugins
    _load_plugins(path, type)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/__init__.py", line 47, in _load_plugins
    im = importlib.import_module('psi.j.{}.{}'.format(type.name, mod.name))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/executors/__init__.py", line 4, in <module>
    from .rp import RPJobExecutor
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/executors/rp.py", line 17, in <module>
    class RPJobExecutor(JobExecutor):
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/src/psi/j/executors/rp.py", line 124, in RPJobExecutor
    def _job_2_descr(self, job: Job) -> Dict[str, Any]:
NameError: name 'Dict' is not defined
```

Solution: add `Dict` to the `from typing import` line

### CODE REVIEW

**Review by andre-merzky — APPROVED** [review]
Thanks, and sorry for the oversight!
I guess I should clean up the linter errors before we merge this.  Do you have a suggestion how to handle the ones related to flux imports?

**Comment by SteVwonder** [comment]
> Do you have a suggestion how to handle the ones related to flux imports?

For now, can we mark `flux` as a missing import? https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports  Once we have a flux conda package, maybe we can run the linter in a conda env.

Alternatively, maybe we can run the linter in the exaworks sdk docker image that has all of the components installed in it.

**Comment by SteVwonder** [comment]
@andre-merzky : I took care of most of the type-checking errors.  The only that I see left is:

```
src/psi/j/executors/flux.py:254: error: "FluxJobExecutor" has no attribute "_tmgr"
```

This appears to be a legitimate missing attribute, not just a type hinting issue.  Could you take a look?  I wasn't sure if this came from radical.utils or radical.pilot (I saw a tmgr in radical.pilot).

**Comment by andre-merzky** [comment]
I will need another work week to close this down.

**Review by jameshcorbett — APPROVED** [review]
LGTM

**Pull request merged**
